name: pull_request

on:
  pull_request:
    paths:
      - '**/*.ttl'

jobs:
  validate-ttl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install rapper
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends raptor2-utils
      - name: Validate ontology TTL
        run: rapper -i turtle ontology/ontology.ttl -c
      - name: Validate knowledge graph TTL
        run: rapper -i turtle ontology/graph.ttl -c
      - name: Validate individual graphs TTLs
        run: |
          for graph in ontology/graphs/*.ttl; do
            rapper -i turtle -c "$graph"
          done

  check-rdf-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Check RDF issues
        run: python scripts/check_rdf_issues.py

  check-rdf-inverses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Check RDF inverses
        run: python scripts/check_rdf_inverses.py

  check-rdf-entities:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Check RDF entities
        run: python scripts/check_rdf_entities.py
